### ISSUE TITLE
cap fps accuratly

### ISSUE THREAD

**Issue by ghost** [Shringe/anyfps-mod#1]
I want to cap fps at exactly 72 fps, I can't do that in sodium. hook me up yeah?

**Comment by Shringe** [comment]
A mod menu screen is currently being worked on to give more control over the mod. For such specific FPS limits, the vanilla bug where the FPS is kept at ~96.2% of the actual set limit will need to be fixed.

**Comment by Shringe** [comment]
Added mod menu support with the ability to cap fps at any value. The vanilla bug still persists but for now you can compensate by increasing the fps limit a little over.
