### ISSUE TITLE
Port to 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [Shringe/anyfps-mod#3]
this mod is the coolest thing i've ever seen, may u port it for 1.21.1? ty

**Comment by ItsPasi** [comment]
Patiently waiting, also please make it compatible with the new sodium beta versions.

**Comment by Shringe** [comment]
Done

**Comment by VaporeonScripts** [comment]
Pls port it to neoforge too,or to make easier the job,mark it as compatible with neoforge and put as required dependency connector and ffapi
